apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-gateway-api-crds.yaml
  - 01-longhorn.yaml
  - 02-longhorn-storageclass.yaml
  - 03-cnpg-operator.yaml
  - 04-traefik.yaml
  - 05-argocd-namespace.yaml
  - 06-argocd-install.yaml
  - 07-erthiscan-app.yaml

patches:
  - target:
      kind: Deployment
      name: traefik
      namespace: traefik
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
  - target:
      labelSelector: "app.kubernetes.io/part-of=argocd"
    patch: |-
      - op: add
        path: /metadata/namespace
        value: argocd
