apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: erthiscan-core
  namespace: erthiscan
spec:
  parentRefs:
    - name: erthiscan-gateway
      namespace: erthiscan
      sectionName: web
    - name: erthiscan-gateway
      namespace: erthiscan
      sectionName: websecure
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: erthiscan-core
          port: 80
