apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 00-erthiscan-namespace.yaml
- 01-postgres-cluster.yaml
- 02-migration-job.yaml
- 03-erthiscan-core.yaml
- 04-service.yaml
- 04a-backend-tls-policy.yaml
- 05-gateway.yaml
- 06-httproute.yaml
- 07-open-facts-import-cronjob.yaml
- 08-postgres-scheduled-backup.yaml
images:
- name: ghcr.io/grigoriitropin/erthiscan-core
  newName: ghcr.io/grigoriitropin/erthiscan-core
  newTag: 5c8a2654bf990f7aad9eeb93354aa60b9e6ae7cc
