apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-erthiscan-namespace.yaml
  - 01-postgres-cluster.yaml
  - 02-migration-job.yaml
  - 03-erthiscan-core.yaml
  - 04-service.yaml
  - 05-gateway.yaml
  - 06-httproute.yaml
  - 07-open-facts-import-cronjob.yaml
