apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-storageclass
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/grigoriitropin/erthiscan-infra.git
    targetRevision: HEAD
    path: longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
